version: "3.9"
services:

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bgp_timeseries
    volumes:
      - timescale-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - bgp-network

  bgp-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: bgp-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TIMESCALE_URI: postgresql://postgres:postgres@timescaledb:5432/bgp_timeseries
      OLLAMA_HOST: host.docker.internal
      OLLAMA_PORT: 11434
    volumes:
      - ./server:/app:cached
    depends_on:
      - timescaledb
    restart: unless-stopped
    networks:
      - bgp-network

networks:
  bgp-network:
    driver: bridge

volumes:
  timescale-data:
